.PHONY: clean All

All:
	@echo "----------Building project:[ BFS - Debug ]----------"
	@cd "BFS" && "$(MAKE)" -f  "BFS.mk"
clean:
	@echo "----------Cleaning project:[ BFS - Debug ]----------"
	@cd "BFS" && "$(MAKE)" -f  "BFS.mk" clean
